name: "🐛 Bug Report"
description: "Create a report to help us improve the project."
title: "fix: [Brief description of the bug]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "When I try to connect the smart sleeve, the app crashes."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide the exact steps to reproduce the behavior."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "What environment are you experiencing the bug in?"
      placeholder: "e.g., iOS 15, Android 12, Web Browser"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context, logs, or screenshots about the problem here."
      placeholder: "If applicable, add screenshots to help explain your problem."